# Generated by Django 5.1.15 on 2026-04-30 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_socialclub'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicdocument',
            name='social_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.socialclub'),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='board_representatives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='content_responsible',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='data_protection_officer',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='external_services_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='finance_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='language_notice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='legal_basis_notice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='membership_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='prevention_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='prevention_notice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='prevention_officer_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='privacy_contact',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='register_court',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='register_entry',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='responsible_person',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='retention_notice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='supervisory_authority',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='tax_number',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='telegram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='vat_id',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='whatsapp_url',
            field=models.URLField(blank=True),
        ),
    ]
