# Generated by Django 5.1.15 on 2026-04-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_socialclubreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialclub',
            name='public_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
