# Generated by Django 5.1.15 on 2026-04-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_socialclub_public_description_socialclub_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialclub',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='social_clubs/banner/'),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='gallery_image_1',
            field=models.ImageField(blank=True, upload_to='social_clubs/gallery/'),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='gallery_image_2',
            field=models.ImageField(blank=True, upload_to='social_clubs/gallery/'),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='gallery_image_3',
            field=models.ImageField(blank=True, upload_to='social_clubs/gallery/'),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='gallery_image_4',
            field=models.ImageField(blank=True, upload_to='social_clubs/gallery/'),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='gallery_image_5',
            field=models.ImageField(blank=True, upload_to='social_clubs/gallery/'),
        ),
        migrations.AddField(
            model_name='socialclub',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='social_clubs/profile/'),
        ),
    ]
