# Generated by Django 5.1.15 on 2026-04-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_socialclub_banner_image_socialclub_gallery_image_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialclub",
            name="federal_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BW", "Baden-Wuerttemberg"),
                    ("BY", "Bayern"),
                    ("BE", "Berlin"),
                    ("BB", "Brandenburg"),
                    ("HB", "Bremen"),
                    ("HH", "Hamburg"),
                    ("HE", "Hessen"),
                    ("MV", "Mecklenburg-Vorpommern"),
                    ("NI", "Niedersachsen"),
                    ("NW", "Nordrhein-Westfalen"),
                    ("RP", "Rheinland-Pfalz"),
                    ("SL", "Saarland"),
                    ("SN", "Sachsen"),
                    ("ST", "Sachsen-Anhalt"),
                    ("SH", "Schleswig-Holstein"),
                    ("TH", "Thueringen"),
                ],
                max_length=2,
            ),
        ),
    ]
