# Generated by Django 5.1.15 on 2026-04-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_socialclub_federal_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialclub",
            name="max_verified_members",
            field=models.PositiveIntegerField(default=500),
        ),
    ]
