# Generated by Django 5.1.15 on 2026-04-30 17:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_socialclubopeninghour"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialclub",
            name="admission_fee",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8),
        ),
        migrations.AddField(
            model_name="socialclub",
            name="monthly_membership_fee",
            field=models.DecimalField(decimal_places=2, default=Decimal("24.00"), max_digits=8),
        ),
    ]
