# Generated by Django 5.1.15 on 2026-04-30 17:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_socialclub_fees"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialclub",
            name="avg_strain_price",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8),
        ),
        migrations.AddField(
            model_name="socialclub",
            name="max_strain_price",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8),
        ),
        migrations.AddField(
            model_name="socialclub",
            name="min_strain_price",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8),
        ),
    ]
