# Generated by Django 5.1.15 on 2026-04-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_socialclub_strain_price_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialclub",
            name="club_bic",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name="socialclub",
            name="club_iban",
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name="socialclub",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="socialclub",
            name="stripe_dashboard_url",
            field=models.URLField(blank=True),
        ),
    ]
