# Generated by Django 5.1.15 on 2026-05-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_socialclub_payment_destination_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialclub',
            name='minimum_age',
            field=models.PositiveSmallIntegerField(default=21),
        ),
    ]
