# Generated by Django 5.2.6 on 2026-03-02 14:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveIntegerField(unique=True)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("total_members", models.PositiveIntegerField(default=0)),
                ("total_grams", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("suspicious_cases", models.PositiveIntegerField(default=0)),
                ("report_data", models.JSONField(blank=True, default=dict)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_compliance_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="PreventionInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provided_at", models.DateTimeField(auto_now_add=True)),
                ("info_version", models.CharField(default="CanG-2024", max_length=32)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "first_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prevention_infos",
                        to="orders.order",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prevention_info",
                        to="members.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-provided_at"],
            },
        ),
        migrations.CreateModel(
            name="SuspiciousActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month_key", models.CharField(db_index=True, max_length=7)),
                ("consumed_grams", models.DecimalField(decimal_places=2, max_digits=8)),
                ("threshold_grams", models.DecimalField(decimal_places=2, default=Decimal("50.00"), max_digits=8)),
                ("detected_at", models.DateTimeField(auto_now=True)),
                ("is_reported", models.BooleanField(default=False)),
                ("reported_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspicious_activities",
                        to="members.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "month_key"),
                        name="unique_profile_month_suspicious_activity",
                    )
                ],
            },
        ),
    ]
