# Generated by Django 5.1.15 on 2026-04-30 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suspiciousactivity',
            options={'ordering': ['-detected_at'], 'verbose_name': 'Verdaechtige Aktivitaet', 'verbose_name_plural': 'Verdaechtige Aktivitaeten'},
        ),
    ]
