# Generated by Django 5.1.15 on 2026-03-09 04:21

import apps.governance.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_inventory_advanced_features'),
        ('members', '0004_profile_members_pro_status_4af664_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('meeting_type', models.CharField(choices=[('board', 'Vorstandssitzung'), ('general', 'Mitgliederversammlung'), ('committee', 'Arbeitskreis')], default='board', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgesagt')], default='planned', max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('minutes_summary', models.TextField(blank=True)),
                ('attendance_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chairperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_meetings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_for', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BoardTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'Offen'), ('in_progress', 'In Arbeit'), ('blocked', 'Blockiert'), ('done', 'Erledigt')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch'), ('critical', 'Kritisch')], default='medium', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_board_tasks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_tasks', to=settings.AUTH_USER_MODEL)),
                ('related_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='governance.boardmeeting')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('integration_type', models.CharField(choices=[('bookkeeping', 'Buchhaltung'), ('printer', 'Drucker / Label'), ('external', 'Externe Club-App')], default='external', max_length=20)),
                ('endpoint_url', models.URLField(blank=True)),
                ('api_key', models.CharField(default=apps.governance.models.default_api_key, max_length=64, unique=True)),
                ('auth_header_name', models.CharField(default='Authorization', max_length=64)),
                ('auth_token', models.CharField(blank=True, max_length=255)),
                ('subscribed_events', models.JSONField(blank=True, default=list)),
                ('resource_scope', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('last_delivery_status', models.CharField(blank=True, max_length=120)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_excerpt', models.CharField(blank=True, max_length=255)),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='governance.integrationendpoint')),
            ],
            options={
                'ordering': ['-delivered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Offen'), ('closed', 'Bearbeitet'), ('deferred', 'Vertagt')], default='open', max_length=20)),
                ('planned_duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='governance.boardmeeting')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_agenda_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('meeting', 'order')},
            },
        ),
        migrations.CreateModel(
            name='MeetingResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('decision_text', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('adopted', 'Beschlossen'), ('rejected', 'Abgelehnt'), ('deferred', 'Vertagt')], default='draft', max_length=20)),
                ('vote_result', models.CharField(blank=True, max_length=120)),
                ('adopted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agenda_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolutions', to='governance.meetingagendaitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resolutions', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='governance.boardmeeting')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MemberCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=40, unique=True)),
                ('qr_token', models.CharField(default=apps.governance.models.default_qr_token, max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateField(default=apps.governance.models.default_card_expiry)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('revoked', 'Entzogen'), ('expired', 'Abgelaufen')], default='active', max_length=20)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_member_cards', to=settings.AUTH_USER_MODEL)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_card', to='members.profile')),
            ],
            options={
                'ordering': ['profile__member_number', 'profile__user__email'],
            },
        ),
        migrations.CreateModel(
            name='OperationalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=48, unique=True)),
                ('record_type', models.CharField(choices=[('transport', 'Transportnachweis'), ('destruction', 'Vernichtungsnachweis')], max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('approved', 'Freigegeben'), ('executed', 'Durchgefuehrt')], default='draft', max_length=24)),
                ('quantity_grams', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origin', models.CharField(blank=True, max_length=255)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('operator_name', models.CharField(blank=True, max_length=160)),
                ('witness_name', models.CharField(blank=True, max_length=160)),
                ('vehicle_identifier', models.CharField(blank=True, max_length=80)),
                ('destruction_method', models.CharField(blank=True, max_length=160)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_operational_records', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operational_records', to=settings.AUTH_USER_MODEL)),
                ('related_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_records', to='members.profile')),
                ('strain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_records', to='inventory.strain')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=64)),
                ('target_model', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('previous_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('entry_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['domain', 'created_at'], name='governance__domain_1e41b6_idx')],
            },
        ),
    ]
