# Generated by Django 5.1.15 on 2026-04-30 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_uploadedinvoice_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancetopup',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Guthaben-Aufladung', 'verbose_name_plural': 'Guthaben-Aufladungen'},
        ),
        migrations.AlterModelOptions(
            name='sepamandate',
            options={'ordering': ['-created_at'], 'verbose_name': 'SEPA-Mandat', 'verbose_name_plural': 'SEPA-Mandate'},
        ),
    ]
