# Generated by Django 5.1.15 on 2026-03-05 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('members', '0003_profile_automation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['status', 'is_verified'], name='members_pro_status_4af664_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['daily_counter_date'], name='members_pro_daily_c_d4ced6_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['monthly_counter_key'], name='members_pro_monthly_d0005d_idx'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('daily_used__lte', 25)), name='daily_limit_25g_check'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_used__lte', 50)), name='monthly_limit_50g_check'),
        ),
    ]
