# Generated by Django 5.1.15 on 2026-04-30 13:15

import apps.members.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_profile_onboarding_extended_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VerificationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('submitted', 'Eingereicht'), ('approved', 'Bestaetigt'), ('rejected', 'Abgelehnt')], default='draft', max_length=16)),
                ('id_front_image', models.FileField(blank=True, upload_to=apps.members.models.verification_upload_path)),
                ('id_back_image', models.FileField(blank=True, upload_to=apps.members.models.verification_upload_path)),
                ('membership_application_document', models.FileField(blank=True, upload_to=apps.members.models.verification_upload_path)),
                ('sepa_mandate_document', models.FileField(blank=True, upload_to=apps.members.models.verification_upload_path)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_member_verifications', to=settings.AUTH_USER_MODEL)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_submission', to='members.profile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
