# Generated by Django 5.1.15 on 2026-04-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_profile_verification_reminder_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="preferred_language",
            field=models.CharField(
                choices=[("de", "Deutsch"), ("en", "Englisch")],
                default="de",
                max_length=2,
            ),
        ),
    ]
