# Generated by Django 5.1.15 on 2026-04-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_profile_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="payment_method_preference",
            field=models.CharField(
                choices=[("sepa", "SEPA-Lastschrift"), ("stripe_card", "Stripe Karte")],
                default="sepa",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="profile",
            name="stripe_payment_method_id",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
