# Generated by Django 5.1.15 on 2026-04-30 20:56

import apps.members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_profile_payment_method_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='monthly_counter_key',
            field=models.CharField(default=apps.members.models.current_month_key, max_length=7),
        ),
    ]
