# Generated by Django 5.1.15 on 2026-05-01 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_alter_profile_monthly_counter_key"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="profile",
            name="daily_limit_25g_check",
        ),
        migrations.RemoveConstraint(
            model_name="profile",
            name="monthly_limit_50g_check",
        ),
    ]
