# Generated by Django 5.1.15 on 2026-05-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0011_remove_profile_limit_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="probation_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
