# Generated by Django 5.1.15 on 2026-05-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_profile_email_verification_and_submission_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('verified', 'Verifiziert'), ('active', 'Aktiv'), ('suspended', 'Gesperrt'), ('rejected', 'Abgelehnt')], default='pending', max_length=16),
        ),
    ]
