# Generated by Django 5.1.15 on 2026-04-30 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_groups'),
        ('core', '0005_socialclub'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.socialclub'),
        ),
    ]
