# Generated by Django 5.1.15 on 2026-03-05 04:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_inventory_advanced_features'),
        ('members', '0004_profile_members_pro_status_4af664_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('expected_harvest_date', models.DateField(verbose_name='Erwartetes Erntedatum')),
                ('actual_harvest_date', models.DateField(blank=True, null=True, verbose_name='Tatsächliches Erntedatum')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Abschlussdatum')),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('active', 'Aktiv'), ('harvested', 'Geerntet'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgebrochen')], default='planned', max_length=20, verbose_name='Status')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Standort')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('compliance_notes', models.TextField(blank=True, verbose_name='Compliance-Notizen (CanG)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grow_cycles', to=settings.AUTH_USER_MODEL)),
                ('responsible_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grow_cycles', to='members.profile', verbose_name='Verantwortliches Mitglied')),
            ],
            options={
                'verbose_name': 'Grow Cycle',
                'verbose_name_plural': 'Grow Cycles',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plant_number', models.CharField(blank=True, max_length=20, verbose_name='Pflanzen-Nummer')),
                ('qr_code_id', models.CharField(blank=True, max_length=100, unique=True, verbose_name='QR-Code ID')),
                ('planting_date', models.DateField(verbose_name='Pflanzdatum')),
                ('harvest_date', models.DateField(blank=True, null=True, verbose_name='Erntedatum')),
                ('status', models.CharField(choices=[('growing', 'Wachsend'), ('vegetative', 'Vegetativ'), ('flowering', 'Blüte'), ('harvested', 'Geerntet'), ('drying', 'Trocknend'), ('curing', 'Aushärtend'), ('completed', 'Abgeschlossen'), ('dead', 'Abgestorben')], default='growing', max_length=20, verbose_name='Status')),
                ('expected_yield_grams', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Erwarteter Ertrag (g)')),
                ('actual_yield_grams', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tatsächlicher Ertrag (g)')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('compliance_notes', models.TextField(blank=True, verbose_name='Compliance-Notizen (CanG)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plants', to=settings.AUTH_USER_MODEL)),
                ('grow_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='cultivation.growcycle', verbose_name='Grow Cycle')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='inventory.strain', verbose_name='Strain')),
            ],
            options={
                'verbose_name': 'Pflanze',
                'verbose_name_plural': 'Pflanzen',
                'ordering': ['grow_cycle', 'plant_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HarvestBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=50, unique=True, verbose_name='Batch-Nummer')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Bezeichnung')),
                ('harvest_date', models.DateField(verbose_name='Erntedatum')),
                ('total_weight_fresh', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Frischgewicht (g)')),
                ('total_weight_dried', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Trockengewicht (g)')),
                ('quality_grade', models.CharField(choices=[('A+', 'A+ (Premium)'), ('A', 'A (Hochwertig)'), ('B', 'B (Standard)'), ('C', 'C (Low)')], default='A', max_length=2, verbose_name='Qualitätsstufe')),
                ('drying_start_date', models.DateField(blank=True, null=True, verbose_name='Trocknungsstart')),
                ('drying_end_date', models.DateField(blank=True, null=True, verbose_name='Trocknungsende')),
                ('curing_start_date', models.DateField(blank=True, null=True, verbose_name='Aushärtungsstart')),
                ('curing_end_date', models.DateField(blank=True, null=True, verbose_name='Aushärtungsende')),
                ('assigned_to_inventory', models.BooleanField(default=False, verbose_name='Dem Inventar zugewiesen')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('compliance_notes', models.TextField(blank=True, verbose_name='Compliance-Notizen (CanG)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_harvest_batches', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_batches', to='inventory.inventoryitem', verbose_name='Inventar-Item')),
                ('plants', models.ManyToManyField(related_name='harvest_batches', to='cultivation.plant', verbose_name='Pflanzen')),
            ],
            options={
                'verbose_name': 'Ernte-Batch',
                'verbose_name_plural': 'Ernte-Batches',
                'ordering': ['-harvest_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlantLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('watering', 'Gießen'), ('fertilizing', 'Düngen'), ('pruning', 'Schneiden/Trimmen'), ('pest_control', 'Schädlingsbekämpfung'), ('transplanting', 'Umtopfen'), ('harvest', 'Ernte'), ('training', 'Training (LST/HST)'), ('observation', 'Beobachtung'), ('other', 'Sonstiges')], max_length=20, verbose_name='Typ')),
                ('date', models.DateTimeField(verbose_name='Datum/Uhrzeit')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('products_used', models.TextField(blank=True, verbose_name='Verwendete Produkte')),
                ('photo_url', models.URLField(blank=True, verbose_name='Foto URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plant_logs', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_logs', to='members.profile', verbose_name='Durchgeführt von')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cultivation.plant', verbose_name='Pflanze')),
            ],
            options={
                'verbose_name': 'Pflanzen-Log',
                'verbose_name_plural': 'Pflanzen-Logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='growcycle',
            index=models.Index(fields=['status', 'start_date'], name='cultivation_status_4c7ecf_idx'),
        ),
        migrations.AddIndex(
            model_name='growcycle',
            index=models.Index(fields=['responsible_member', 'status'], name='cultivation_respons_9d5707_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['grow_cycle', 'status'], name='cultivation_grow_cy_83e05f_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['strain', 'status'], name='cultivation_strain__58c953_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['qr_code_id'], name='cultivation_qr_code_d96769_idx'),
        ),
        migrations.AddIndex(
            model_name='harvestbatch',
            index=models.Index(fields=['harvest_date', 'quality_grade'], name='cultivation_harvest_3f3536_idx'),
        ),
        migrations.AddIndex(
            model_name='harvestbatch',
            index=models.Index(fields=['assigned_to_inventory', 'harvest_date'], name='cultivation_assigne_93bd20_idx'),
        ),
        migrations.AddIndex(
            model_name='plantlog',
            index=models.Index(fields=['plant', 'log_type', 'date'], name='cultivation_plant_i_7f20ff_idx'),
        ),
        migrations.AddIndex(
            model_name='plantlog',
            index=models.Index(fields=['performed_by', 'date'], name='cultivation_perform_940abe_idx'),
        ),
    ]
