# Generated by Django 5.1.15 on 2026-03-05 04:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_profile_automation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Gruppenname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'E-Mail-Gruppe',
                'verbose_name_plural': 'E-Mail-Gruppen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MassEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255, verbose_name='Betreff')),
                ('content', models.TextField(verbose_name='Inhalt (Markdown)')),
                ('content_html', models.TextField(blank=True, verbose_name='Inhalt (HTML)')),
                ('recipient_type', models.CharField(choices=[('all', 'Alle Mitglieder'), ('group', 'Bestimmte Gruppe'), ('individual', 'Individuelle Auswahl')], default='all', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('queued', 'In Warteschlange'), ('sending', 'Wird gesendet'), ('sent', 'Gesendet'), ('failed', 'Fehlgeschlagen'), ('cancelled', 'Abgebrochen')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Geplante Sendezeit')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('opened_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mass_emails', to=settings.AUTH_USER_MODEL)),
                ('individual_recipients', models.ManyToManyField(blank=True, related_name='individual_emails', to='members.profile', verbose_name='Individuelle Empfänger')),
                ('recipient_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.emailgroup', verbose_name='Empfängergruppe')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_mass_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Massen-E-Mail',
                'verbose_name_plural': 'Massen-E-Mails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='messaging.emailgroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_groups', to='members.profile')),
            ],
            options={
                'verbose_name': 'Gruppenmitglied',
                'verbose_name_plural': 'Gruppenmitglieder',
                'unique_together': {('group', 'member')},
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('sent', 'Gesendet'), ('delivered', 'Zugestellt'), ('opened', 'Geöffnet'), ('failed', 'Fehlgeschlagen'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='members.profile')),
                ('mass_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='messaging.massemail')),
            ],
            options={
                'verbose_name': 'E-Mail-Log',
                'verbose_name_plural': 'E-Mail-Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mass_email', 'status'], name='messaging_e_mass_em_79f2e3_idx'), models.Index(fields=['member', 'created_at'], name='messaging_e_member__946428_idx')],
            },
        ),
    ]
