# Generated by Django 5.1.15 on 2026-03-05 04:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_profile_members_pro_status_4af664_idx_and_more'),
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsCostLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=7, verbose_name='Monat (YYYY-MM)')),
                ('total_messages', models.IntegerField(default=0, verbose_name='Gesamtanzahl')),
                ('total_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Gesamtkosten (€)')),
                ('provider_breakdown', models.JSONField(default=dict, verbose_name='Provider-Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS-Kosten-Log',
                'verbose_name_plural': 'SMS-Kosten-Logs',
                'ordering': ['-month'],
                'unique_together': {('month',)},
            },
        ),
        migrations.CreateModel(
            name='SmsProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('twilio', 'Twilio'), ('vonage', 'Vonage'), ('custom', 'Custom Webhook')], max_length=20, verbose_name='Provider')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='API Secret')),
                ('sender_number', models.CharField(max_length=20, verbose_name='Absendernummer')),
                ('webhook_url', models.URLField(blank=True, verbose_name='Webhook URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('cost_per_sms', models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Kosten pro SMS (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sms_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS-Provider',
                'verbose_name_plural': 'SMS-Provider',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('content', models.TextField(max_length=1600, verbose_name='Vorlage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sms_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS-Vorlage',
                'verbose_name_plural': 'SMS-Vorlagen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('individual', 'Einzelner Empfänger'), ('group', 'Gruppe')], default='individual', max_length=20)),
                ('recipient_phone', models.CharField(blank=True, max_length=20, verbose_name='Empfängernummer')),
                ('content', models.TextField(max_length=1600, verbose_name='Nachricht')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('queued', 'In Warteschlange'), ('sending', 'Wird gesendet'), ('sent', 'Gesendet'), ('delivered', 'Zugestellt'), ('failed', 'Fehlgeschlagen')], default='draft', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255, verbose_name='Externe ID')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gesendet am')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Zugestellt am')),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Kosten (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sms_messages', to=settings.AUTH_USER_MODEL)),
                ('recipient_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='messaging.emailgroup', verbose_name='Empfängergruppe')),
                ('recipient_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='members.profile', verbose_name='Empfänger (Mitglied)')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_sms_messages', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.smsproviderconfig', verbose_name='SMS-Provider')),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.smstemplate', verbose_name='Verwendetes Template')),
            ],
            options={
                'verbose_name': 'SMS-Nachricht',
                'verbose_name_plural': 'SMS-Nachrichten',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='messaging_s_status_751778_idx'), models.Index(fields=['recipient_member', 'created_at'], name='messaging_s_recipie_f0f484_idx')],
            },
        ),
    ]
