# Generated by Django 5.1.15 on 2026-05-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserviert'), ('completed', 'Abgeschlossen'), ('cancelled', 'Storniert'), ('expired', 'Abgelaufen')], default='reserved', max_length=20),
        ),
    ]
