# Generated by Django 5.1.15 on 2026-04-30 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_socialclub_strain_price_stats"),
        ("inventory", "0006_strain_extended_product_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="strain",
            name="social_club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strains",
                to="core.socialclub",
            ),
        ),
        migrations.AlterField(
            model_name="strain",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name="strain",
            constraint=models.UniqueConstraint(fields=("social_club", "name"), name="uniq_strain_name_per_social_club"),
        ),
    ]
