# Generated by Django 5.1.15 on 2026-04-30 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_strain_add_cannabinoids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': 'Charge', 'verbose_name_plural': 'Chargen'},
        ),
    ]
